version: "3.6"
services:
  test-boot:
    container_name: test-boot
    image: test-boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILE: prod