server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10011/replication_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect